### PR TITLE
enable ivy and sbt cache

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by gmethvin** [comment]
@graingert do you mind rebasing and squashing so there's just one commit? Thanks.

**Comment by graingert** [comment]
@gmethvin there is only one commit it's a bug in GitHub. Try doing a merge locally and looking at the commit graph

**Comment by graingert** [comment]
@gmethvin I pushed a fake commit, and then restored this one. It's now showing just one commit

**Comment by gmethvin** [comment]
Okay thanks.

**Pull request merged**
