### PR TITLE
Redis play 2.4

### PR DESCRIPTION
**Pull request by rmmeans**
First pass at a fix for #145 

Points of interest:
- Supports named cache just like the new EhCache impl does with the reference impl.
- Can work side-by-side with the default cache, by default if you just add the module as a library dependency in your build file then it will continue to allow the reference impl (EhCache) to be the default cache and you can use named cache providers for redis cache.
- If you turn off the reference impl, then the Redis cache will assume it should be the default cache provider for any non-named cache instances.
- renamed package structure (will need feedback on this) since there is no longer plugins.

### CODE REVIEW

**Comment by jroper** [comment]
Looks good to me.

Since the package name is being renamed anyway, I think it makes sense to rename it to `com.typesafe.play.redis`.

It'd be good to see at least a simple test that started a Play application and had a redis cache injected, to make sure the bindings work.  You can add a redis server to travis easily:

http://docs.travis-ci.com/user/database-setup/#Redis

**Comment by rmmeans** [comment]
Cool. I'll see if I can spend some time with the testing part soon.

I've renamed the package structure like you requested -- In my commits I also had renamed the product name and org, any feedback on that, or is that fine?

**Comment by jroper** [comment]
I think it's fine.

**Comment by rmmeans** [comment]
I've added tests - good thing too, as it helped me catch an issue with the Cached results that changed in play 2.4 with the addition of SerializableResult. I'm using Redis via travis like you suggested. 

I'm done with this unless you see more changes that are necessary.

**Comment by jroper** [comment]
Released as `"com.typesafe.play.modules" % "play-modules-redis" % "2.4.0"`.

**Pull request merged**
